
import { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'The Obsidian Waterfront',
    price: 18500000,
    address: '42 Royal Palm Way',
    city: 'Miami',
    bedrooms: 6,
    bathrooms: 8,
    sqft: 8200,
    type: 'House',
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1600',
    description: 'A masterpiece of contemporary architecture, The Obsidian offers unparalleled bay views and a private 100-foot deep-water dock. This residence is defined by its seamless indoor-outdoor flow and ultra-premium finishes.',
    features: ['Infinity Edge Pool', 'Private Dock', 'Staff Quarters', 'Home Wellness Center'],
    coordinates: { lat: 25.7617, lng: -80.1918 }
  },
  {
    id: '2',
    title: 'Summit Sky Penthouse',
    price: 9850000,
    address: '100 Brickell Plaza',
    city: 'Miami',
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4500,
    type: 'Condo',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1600',
    description: 'Experience the pinnacle of urban living. This duplex penthouse features double-height ceilings, a private rooftop terrace with a plunge pool, and panoramic vistas of the Atlantic skyline.',
    features: ['Private Rooftop Pool', '24-Hour Butler Service', 'Private Elevator', 'Wine Gallery'],
    coordinates: { lat: 25.7650, lng: -80.1900 }
  },
  {
    id: '3',
    title: 'The Heritage Estate',
    price: 6250000,
    address: '1200 Old Cutler Rd',
    city: 'Coral Gables',
    bedrooms: 5,
    bathrooms: 6,
    sqft: 6100,
    type: 'House',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1600',
    description: 'A historic Mediterranean revival estate nestled within lush oak canopies. Meticulously restored to provide modern luxury while honoring its architectural lineage.',
    features: ['Gated Entrance', 'Summer Kitchen', 'Original Tile Work', 'Secret Garden'],
    coordinates: { lat: 25.7490, lng: -80.2630 }
  },
  {
    id: '4',
    title: 'Vue Urban Lofts',
    price: 3150000,
    address: '55 Wynwood Ave',
    city: 'Miami',
    bedrooms: 3,
    bathrooms: 3,
    sqft: 3200,
    type: 'Apartment',
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=1600',
    description: 'Artistry meets industry in this expansive Wynwood loft. Featuring gallery-grade lighting, polished concrete floors, and a professional-grade catering kitchen.',
    features: ['Exposed Concrete', 'Chef\'s Kitchen', 'Rooftop Lounge', 'Private Art Gallery'],
    coordinates: { lat: 25.8010, lng: -80.1990 }
  },
  {
    id: '5',
    title: 'Azure Terrace',
    price: 5450000,
    address: '12 Ocean Blvd',
    city: 'Key Biscayne',
    bedrooms: 3,
    bathrooms: 4,
    sqft: 3400,
    type: 'Condo',
    imageUrl: 'https://images.unsplash.com/photo-1512918766671-ad650796207b?auto=format&fit=crop&q=80&w=1600',
    description: 'Exclusive beachfront residence with expansive wrap-around terraces. Every room provides sweeping views of the turquoise Atlantic waters.',
    features: ['Beach Access', 'Lap Pool', 'Private Fitness Studio', 'Tennis Center'],
    coordinates: { lat: 25.6938, lng: -80.1628 }
  },
  {
    id: '6',
    title: 'The Artisan Sanctuary',
    price: 8900000,
    address: '300 Tiger Tail Ave',
    city: 'Coconut Grove',
    bedrooms: 5,
    bathrooms: 5,
    sqft: 6800,
    type: 'House',
    imageUrl: 'https://images.unsplash.com/photo-1505843513577-22bb7d21ef45?auto=format&fit=crop&q=80&w=1600',
    description: 'Tucked away in the secluded groves, this modern sanctuary blends natural limestone with sustainable wood design for the ultimate private retreat.',
    features: ['Tropical Courtyard', 'Heated Saltwater Pool', 'Guest Wing', 'Automated Security'],
    coordinates: { lat: 25.7285, lng: -80.2415 }
  }
];
